# Spring Boot 应用程序的配置文件

# 服务器端口配置
server:
  port: 8000

## 数据库连接配置 aws
spring:
  datasource:
    url: jdbc:mysql://database-mysql.cli4qmaoiviu.ap-northeast-1.rds.amazonaws.com:3306/social
    username: shuAdmin
    password: ShihHsinabc123
    driver-class-name: com.mysql.cj.jdbc.Driver


# 数据库连接配置 localhost
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/social
#    username: root
#    password: abc123
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: AUTO
        field-strategy: not_empty
        db-type: mysql
        strict-mode: true
  configuration-properties:
    hump-to-underline: true


ipfs:
  config:
    multi-addr: /ip4/127.0.0.1/tcp/5001 # ipfs的服务器地址和端口

# 日志配置
logging:
  level:
    root: INFO
    com.shihHsin: DEBUG


